/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * API specification for personal code editor with AI analysis and GitHub integration
 * OpenAPI spec version: 0.1.0
 */
import * as zod from "zod";

/**
 * Returns server health status
 * @summary Health check
 */
export const HealthCheckResponse = zod.object({
  status: zod.string(),
});

/**
 * @summary Import a project directly from a GitHub repository URL
 */
export const ImportFromGithubBody = zod.object({
  repoUrl: zod
    .string()
    .describe("GitHub repository URL (e.g. https:\/\/github.com\/owner\/repo)"),
  branch: zod
    .string()
    .nullish()
    .describe("Branch to import (defaults to default branch)"),
});

/**
 * @summary List all uploaded projects
 */
export const ListProjectsResponseItem = zod.object({
  id: zod.string(),
  name: zod.string(),
  createdAt: zod.string(),
  fileCount: zod.number(),
  sizeBytes: zod.number(),
});
export const ListProjectsResponse = zod.array(ListProjectsResponseItem);

/**
 * @summary Upload a ZIP file to create a new project
 */
export const UploadProjectBody = zod.object({
  file: zod.instanceof(File),
  name: zod.string().optional(),
});

/**
 * @summary Get project details including file tree
 */
export const GetProjectParams = zod.object({
  projectId: zod.coerce.string(),
});

export const GetProjectResponse = zod.object({
  id: zod.string(),
  name: zod.string(),
  createdAt: zod.string(),
  fileCount: zod.number(),
  sizeBytes: zod.number(),
  tree: zod.object({
    name: zod.string(),
    path: zod.string(),
    type: zod.enum(["file", "directory"]),
    children: zod.array(zod.unknown()).optional(),
  }),
});

/**
 * @summary Delete a project
 */
export const DeleteProjectParams = zod.object({
  projectId: zod.coerce.string(),
});

/**
 * @summary Get the content of a specific file within a project
 */
export const GetFileContentParams = zod.object({
  projectId: zod.coerce.string(),
});

export const GetFileContentQueryParams = zod.object({
  path: zod.coerce
    .string()
    .describe("The relative path to the file within the project"),
});

export const GetFileContentResponse = zod.object({
  path: zod.string(),
  content: zod.string(),
  language: zod.string(),
  isBinary: zod.boolean(),
});

/**
 * @summary Create or overwrite a file within a project
 */
export const WriteFileParams = zod.object({
  projectId: zod.coerce.string(),
});

export const WriteFileBody = zod.object({
  path: zod
    .string()
    .describe("Relative path of the file to write (will create parent dirs)"),
  content: zod.string().describe("Full content to write to the file"),
});

export const WriteFileResponse = zod.object({
  path: zod.string(),
  message: zod.string(),
});

/**
 * @summary Delete a file within a project
 */
export const DeleteFileParams = zod.object({
  projectId: zod.coerce.string(),
});

export const DeleteFileQueryParams = zod.object({
  path: zod.coerce.string(),
});

/**
 * @summary Execute a shell command in the project directory
 */
export const ExecCommandParams = zod.object({
  projectId: zod.coerce.string(),
});

export const ExecCommandBody = zod.object({
  command: zod.string().describe("Shell command to execute"),
  timeout: zod
    .number()
    .nullish()
    .describe("Timeout in milliseconds (default 30000, max 120000)"),
});

export const ExecCommandResponse = zod.object({
  stdout: zod.string(),
  stderr: zod.string(),
  exitCode: zod.number(),
  durationMs: zod.number(),
});

/**
 * @summary Send a free-form message to the AI with optional file context
 */
export const AiChatBody = zod.object({
  messages: zod.array(
    zod.object({
      role: zod.enum(["user", "assistant"]),
      content: zod.string(),
    }),
  ),
  fileContext: zod
    .string()
    .nullish()
    .describe("Optional file content to inject as context"),
  filePath: zod
    .string()
    .nullish()
    .describe("Optional file path for context label"),
  projectId: zod
    .string()
    .nullish()
    .describe("Project ID to load full project context on the server"),
  projectContext: zod
    .boolean()
    .nullish()
    .describe("If true, all project files will be loaded as context"),
  terminalContext: zod
    .string()
    .nullish()
    .describe("Recent terminal output to inject as context for AI"),
});

export const AiChatResponse = zod.object({
  reply: zod.string(),
  model: zod.string(),
});

/**
 * @summary Analyze a single file using configured AI
 */
export const AnalyzeFileBody = zod.object({
  projectId: zod.string(),
  filePath: zod.string(),
  content: zod.string(),
});

export const AnalyzeFileResponse = zod.object({
  analysis: zod.string(),
  model: zod.string(),
});

/**
 * @summary Analyze a folder's contents using configured AI
 */
export const AnalyzeFolderBody = zod.object({
  projectId: zod.string(),
  folderPath: zod.string(),
});

export const AnalyzeFolderResponse = zod.object({
  analysis: zod.string(),
  model: zod.string(),
});

/**
 * @summary Create a GitHub repository and push all project files
 */
export const CreateGithubRepoBody = zod.object({
  projectId: zod.string(),
  repoName: zod.string(),
  description: zod.string().nullish(),
  isPrivate: zod.boolean(),
});

export const CreateGithubRepoResponse = zod.object({
  repoUrl: zod.string(),
  repoName: zod.string(),
  filesCommitted: zod.number(),
});

/**
 * @summary Get current settings (without sensitive values)
 */
export const GetSettingsResponse = zod.object({
  aiApiKeySet: zod.boolean(),
  aiBaseUrl: zod.string().nullish(),
  aiModel: zod.string().nullish(),
  githubTokenSet: zod.boolean(),
});

/**
 * @summary Update settings
 */
export const UpdateSettingsBody = zod.object({
  aiApiKey: zod.string().nullish(),
  aiBaseUrl: zod.string().nullish(),
  aiModel: zod.string().nullish(),
  githubToken: zod.string().nullish(),
});

export const UpdateSettingsResponse = zod.object({
  aiApiKeySet: zod.boolean(),
  aiBaseUrl: zod.string().nullish(),
  aiModel: zod.string().nullish(),
  githubTokenSet: zod.boolean(),
});
