/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * API specification for personal code editor with AI analysis and GitHub integration
 * OpenAPI spec version: 0.1.0
 */
import type { ChatMessage } from "./chatMessage";

export interface AiChatRequest {
  messages: ChatMessage[];
  /**
   * Optional file content to inject as context
   * @nullable
   */
  fileContext?: string | null;
  /**
   * Optional file path for context label
   * @nullable
   */
  filePath?: string | null;
  /**
   * Project ID to load full project context on the server
   * @nullable
   */
  projectId?: string | null;
  /**
   * If true, all project files will be loaded as context
   * @nullable
   */
  projectContext?: boolean | null;
  /**
   * Recent terminal output to inject as context for AI
   * @nullable
   */
  terminalContext?: string | null;
}
