/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * API specification for personal code editor with AI analysis and GitHub integration
 * OpenAPI spec version: 0.1.0
 */

export interface ExecCommandRequest {
  /** Shell command to execute */
  command: string;
  /**
   * Timeout in milliseconds (default 30000, max 120000)
   * @nullable
   */
  timeout?: number | null;
}
