/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * API specification for personal code editor with AI analysis and GitHub integration
 * OpenAPI spec version: 0.1.0
 */

export type FileNodeType = (typeof FileNodeType)[keyof typeof FileNodeType];

export const FileNodeType = {
  file: "file",
  directory: "directory",
} as const;
