/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * API specification for personal code editor with AI analysis and GitHub integration
 * OpenAPI spec version: 0.1.0
 */

export interface ImportGithubRequest {
  /** GitHub repository URL (e.g. https://github.com/owner/repo) */
  repoUrl: string;
  /**
   * Branch to import (defaults to default branch)
   * @nullable
   */
  branch?: string | null;
}
