/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * API specification for personal code editor with AI analysis and GitHub integration
 * OpenAPI spec version: 0.1.0
 */
import type { FileNode } from "./fileNode";

export interface ProjectDetail {
  id: string;
  name: string;
  createdAt: string;
  fileCount: number;
  sizeBytes: number;
  tree: FileNode;
}
