/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * API specification for personal code editor with AI analysis and GitHub integration
 * OpenAPI spec version: 0.1.0
 */

export interface WriteFileRequest {
  /** Relative path of the file to write (will create parent dirs) */
  path: string;
  /** Full content to write to the file */
  content: string;
}
